
import React from 'react';

const DisclaimerSection = () => {
  return (
    <section id="disclaimer" className="py-24 relative overflow-hidden">
      <div className="absolute inset-0 star-field opacity-20"></div>
      <div className="container max-w-4xl mx-auto px-4 md:px-8 relative z-10">
        <div className="text-center mb-16">
          <span className="inline-block px-4 py-1 mb-4 rounded-full bg-neon-orange/20 text-neon-orange text-sm font-medium border border-neon-orange/30">
            Important Information
          </span>
          <h2 className="text-4xl md:text-5xl font-bold mb-6 text-white text-glow">
            Legal Disclaimer
          </h2>
          <p className="text-xl text-gray-300 max-w-3xl mx-auto">
            Please review the following information regarding the use of Imagination Traveler GPT
          </p>
        </div>

        <div className="glass-panel rounded-xl p-6 md:p-8">
          <div className="space-y-6 text-gray-300 leading-relaxed">
            <p>
              <strong className="text-white">Fictional Content Disclaimer:</strong> Imagination Traveler GPT generates fictional content based on user prompts. All dimensions, narratives, characters, and images produced are works of fiction and do not represent real events, predictions, scientific theories, or factual information unless explicitly stated otherwise.
            </p>
            
            <p>
              <strong className="text-white">Not Professional Advice:</strong> Content generated by Imagination Traveler GPT should not be interpreted as professional, scientific, historical, medical, legal, or financial advice. For factual information on scientific theories, historical events, or other specialized topics, please consult qualified professionals or reliable academic sources.
            </p>
            
            <p>
              <strong className="text-white">Image Generation:</strong> Images generated by the tool are created using AI technology and do not depict real locations, people, or events. Any resemblance to actual places, persons, or occurrences is coincidental. Images are for entertainment and illustrative purposes only.
            </p>
            
            <p>
              <strong className="text-white">Limitations of AI:</strong> As an AI system, Imagination Traveler GPT has limited knowledge and may occasionally produce responses that contain inaccuracies, inconsistencies, or content that lacks scientific basis despite our efforts to ground narratives in theoretical possibility.
            </p>
            
            <p>
              <strong className="text-white">Content Appropriateness:</strong> While we strive to ensure content remains appropriate, users are responsible for their prompts and how they use the information provided. Users should refrain from attempting to generate harmful, illegal, or explicit content.
            </p>
            
            <p>
              <strong className="text-white">User Responsibility:</strong> By using Imagination Traveler GPT, you agree to use it responsibly and acknowledge that AI Web Tools LLC is not responsible for any actions taken based on the content generated by this tool.
            </p>
            
            <p>
              <strong className="text-white">Third-Party Services:</strong> Imagination Traveler GPT operates through OpenAI's platform and is subject to their terms of service and privacy policy in addition to our own.
            </p>
            
            <p>
              <strong className="text-white">Copyright and IP:</strong> AI Web Tools LLC retains appropriate rights to the Imagination Traveler GPT service itself. Content generated in collaboration with users may be subject to various intellectual property considerations as outlined in OpenAI's terms of service.
            </p>
            
            <p>
              <strong className="text-white">Service Availability:</strong> AI Web Tools LLC does not guarantee uninterrupted access to Imagination Traveler GPT and reserves the right to modify, suspend, or discontinue the service at any time without notice.
            </p>
            
            <p className="text-sm text-gray-500 pt-4 border-t border-gray-800">
              This disclaimer may be updated periodically. Last updated: May 2025
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default DisclaimerSection;
